/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "tests/check_ball.check.c" instead.
 */

#include <check.h>

#include "../src/main.h"

// unit testing below
// checkmk tests/check_ball.check.c > tests/check_ball.c
START_TEST(test_calculate_velocity_collision) {
    fail_unless(calculate_velocity_collision(100.f) == -80.f, "Incorrect velocity calculation");
}
END_TEST

START_TEST(test_get_time) {
    fail_if(get_time(0) == 0, "get_time(0) failed");
    fail_unless(get_time(0) >= get_time(1), "get_time broken");
}
END_TEST

START_TEST(test_set_pos) {
    ball_t* ball = malloc(sizeof(ball_t));
    set_pos(ball);
    memset(ball, 0, sizeof(ball_t));
    fail_unless(ball->p.x == 0 && ball->p.y == 0, "null ball gives bad behavior");
    memset(ball, 0, sizeof(ball_t));
    ball->G = -9.81f;
    ball->dtx = 2.5f;
    ball->dty = 2.5f;
    ball->v_x = 12;
    ball->v_y = 43;
    set_pos(ball);
    char* msg = malloc(100);
    sprintf(msg, "expected x=30 and y=77, recieved instead x=%2.f and y=%d", ball->p.x, (int)roundf(ball->p.y));
    fail_unless(ball->p.x == 30 && roundf(ball->p.y) == 77, msg);
    free(msg);
    free(ball);
}

int main(void)
{
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("calculate_velocity_collision");
    TCase *tc1_2 = tcase_create("get_time");
    TCase *tc1_3 = tcase_create("set_pos");
    SRunner *sr = srunner_create(s1);

    int nf;

    suite_add_tcase(s1, tc1_1);
    suite_add_tcase(s1, tc1_2);
    suite_add_tcase(s1, tc1_3);
    tcase_add_test(tc1_1, test_calculate_velocity_collision);
    tcase_add_test(tc1_2, test_get_time);
    tcase_add_test(tc1_3, test_set_pos);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
